### ISSUE TITLE
bitcoin.circom doesn't have `step_out`

### ISSUE THREAD

**Issue by 0xbok** [nalinbhardwaj/Nova-Scotia#28]
https://github.com/nalinbhardwaj/Nova-Scotia#writing-nova-step-circuits-in-circom says a circuit needs to have the same number of public inputs and outputs (`step_in` and `step_out`), but bitcoin circuit only has `step_in`: https://github.com/nalinbhardwaj/Nova-Scotia/blob/main/examples/bitcoin/circom/bitcoin_benchmark.circom#L176

Is that a bug or is `step_out` not required?

**Comment by nalinbhardwaj** [comment]
It is not strictly required but recommended. In reality it takes all public outputs of the circuit as the output of the step circuit, but that means ordering of these is determined by the circom compiler. By using “step_out” we ensure the ordering of the output is controlled tn the developer (preventing errant bugs)
