### ISSUE TITLE
Making Nova-Scotia work with BN254/grumpkin cycle

### ISSUE THREAD

**Issue by 0xbok** [nalinbhardwaj/Nova-Scotia#29]
I'm interested in making Nova-Scotia work with BN254/grumpkin cycle so that we can have Nova output in a groth16 verifier. Any guidelines are appreciated!

**Comment by chaosma** [comment]
@0xbok I added the BN254/grumpkin cycle support in this branch: https://github.com/chaosma/Nova-Scotia/tree/feature/curve-grumpkin

In order to do so, I have to modify the `nova` and `halo2curves` repo as well.

**Comment by 0xbok** [comment]
thanks @chaosma, did you see https://twitter.com/leonardoalt/status/1671962194081095689. looks like the modification for `nova` and `halo2curve` is already in progess.

**Comment by chaosma** [comment]
Yes. I have also discussed with Han on the halo2curve modification

**Comment by nalinbhardwaj** [comment]
This is now supported in master. See [`toy_bn254.rs`](https://github.com/nalinbhardwaj/Nova-Scotia/blob/main/examples/toy_bn254.rs)
