### ISSUE TITLE
Browser Test

### ISSUE THREAD

**Issue by Hakkush-07** [nalinbhardwaj/Nova-Scotia#35]
Example website (https://effulgent-liger-07e9d0.netlify.app/) gives error when proving.
It lastly prints "Creating a RecursiveSNARK..." to the console and gives "Uncaught (in promise) RuntimeError: Unreachable" error.
I get the same error when I try in my local.
![image](https://github.com/nalinbhardwaj/Nova-Scotia/assets/68596831/09689d5e-27e2-4cda-b6a1-9112dbbc7932)

**Comment by nalinbhardwaj** [comment]
I just ran the build locally from `main` `yarn start` in `browser-test/test-client` and it still seems to work for me:

<img width="961" alt="image" src="https://github.com/nalinbhardwaj/Nova-Scotia/assets/6984346/03745192-258e-406a-8a6c-6480e0c8306e">

What browser/versions etc. are you on? Here's mine if helpful:
<img width="620" alt="image" src="https://github.com/nalinbhardwaj/Nova-Scotia/assets/6984346/919e532d-3c7a-4ada-a46f-7424ea29a9e5">

**Comment by nalinbhardwaj** [comment]
Going to close since not reproducible, feel free to re-open if you have more
