### ISSUE TITLE
example repo's error, can't read toy.cpp or toy.wasm

### ISSUE THREAD

**Issue by yugonsan** [nalinbhardwaj/Nova-Scotia#36]
Excuse me, and I ran the example's code, which is named toy_bn254.rs, with this terminal command "cargo run --release --example toy_bn254" in the toy directory. However, toy_bn254 seemed that the code couldn't open the toy.cpp or toy.wasm. Could you tell me how to solve this problem? Sorry, thanks.
Here is the error message I received.
```
Running test with witness generator: examples/toy/bn254/toy_cpp/toy and group: halo2curves::bn256::curve::G1
thread 'main' panicked at 'unable to open.: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /Users/(omission)/Nova-Scotia/src/circom/reader.rs:243:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by nalinbhardwaj** [comment]
As described in the README, you need to install circom and run the compile step for circuit (as in the [CI setup](https://github.com/nalinbhardwaj/Nova-Scotia/blob/main/.github/workflows/test.yml#L20-L29) as well:
1. Install Circom
2. Run `examples/toy/compile.sh`
